export const ADDINGREDIENT = "ADDINGREDIENT";
export const DELINGREDIENT = "DELINGREDIENT";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START  = "PURCHASE_BURGER_START";

export const PURCHASE_INIT = "PURCHASE_INIT";


export const FETECH_ORDERS_INIT = "FETECH_ORDERS_INIT";
export const FETECH_ORDERS_START = "FETECH_ORDERS_START";
export const FETECH_ORDERS_SUCESS = "FETECH_ORDERS_SUCESS";
export const FETECH_ORDERS_FAIL = "FETECH_ORDERS_FAIL";


export const AUTH_START = "AUTH_START";
export const AUTH_SUCESS = "AUTH_SUCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
